const fs = require("fs");
const child_process = require("child_process");

const opamDefinition = fs.readFileSync("rescript-react-intl-extractor.opam");
const packageVersion = /^version: "(.*)"$/gm.exec(opamDefinition)[1];

const reScriptVersion = child_process
  .execSync("git submodule")
  .toString()
  .trim()
  .split(" ")[0]
  .substring(0, 7);

const version = `${packageVersion} (ReScript ${reScriptVersion})`;

fs.writeFileSync(
  "bin/Version.ml",
  `(*** GENERATED BY setVersion.js ***)

let version = "${version}"
`
);

console.log(`Version set to ${version}`);
